---
title: "jlenv: Robust Julia management for your applications."
email: mark@taqtiqa.com
description: > # this means to ignore newlines until "baseurl:"
  Manage multiple versions of <a href="https://www.julialang.org/">Julia</a>
github_username:  jlenv
include_related_posts: true
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
remote_theme: orderedlist/minimal
relative_links:
  enabled: true
  collections: true
